forge "http://forge.puppetlabs.com"
  mod "puppetlabs/java",	 			"1.0.1"
  mod "puppetlabs/firewall", 			"0.4.2"
  mod "puppetlabs/apache" ,  			"0.9.0"
  mod "puppetlabs/motd",     			"1.0.1"
  mod "smarchive/archive",   			"0.1.1"
  mod "elasticsearch/elasticsearch",    "0.2.2" 
  mod "ispavailability/logstash",       "0.3.4"